# @package _global_

# uses only 5 batches of the training data and 2 batches of validation/test data

defaults:
  - default

trainer:
  max_epochs: 3
  limit_train_batches: 5
  limit_val_batches: 2
  limit_test_batches: 2
